<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $settings_countries = array(
            array('id' => '1', 'country_label' => 'Nigeria', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '2', 'country_label' => 'Afghanistan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '3', 'country_label' => 'Aland Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '4', 'country_label' => 'Albania', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '5', 'country_label' => 'Algeria', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '6', 'country_label' => 'American Samoa', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '7', 'country_label' => 'Andorra', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '8', 'country_label' => 'Angola', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '9', 'country_label' => 'Anguilla', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '10', 'country_label' => 'Antarctica', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '11', 'country_label' => 'Antigua and Barbuda', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '12', 'country_label' => 'Argentina', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '13', 'country_label' => 'Armenia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '14', 'country_label' => 'Aruba', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '15', 'country_label' => 'Australia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '16', 'country_label' => 'Austria', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '17', 'country_label' => 'Azerbaijan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '18', 'country_label' => 'Bahamas', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '19', 'country_label' => 'Bahrain', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '20', 'country_label' => 'Bangladesh', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '21', 'country_label' => 'Barbados', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '22', 'country_label' => 'Belarus', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '23', 'country_label' => 'Belgium', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '24', 'country_label' => 'Belize', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '25', 'country_label' => 'Benin', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '26', 'country_label' => 'Bermuda', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '27', 'country_label' => 'Bhutan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '28', 'country_label' => 'Bolivia, Plurinational State of bolivia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '29', 'country_label' => 'Bosnia and Herzegovina', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '30', 'country_label' => 'Botswana', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '31', 'country_label' => 'Brazil', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '32', 'country_label' => 'British Indian Ocean Territory', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '33', 'country_label' => 'Brunei Darussalam', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '34', 'country_label' => 'Bulgaria', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '35', 'country_label' => 'Burkina Faso', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '36', 'country_label' => 'Burundi', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '37', 'country_label' => 'Cambodia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '38', 'country_label' => 'Cameroon', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '39', 'country_label' => 'Canada', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '40', 'country_label' => 'Cape Verde', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '41', 'country_label' => 'Cayman Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '42', 'country_label' => 'Central African Republic', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '43', 'country_label' => 'Chad', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '44', 'country_label' => 'Chile', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '45', 'country_label' => 'China', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '46', 'country_label' => 'Christmas Island', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '47', 'country_label' => 'Cocos (Keeling) Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '48', 'country_label' => 'Colombia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '49', 'country_label' => 'Comoros', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '50', 'country_label' => 'Congo', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '51', 'country_label' => 'Congo, The Democratic Republic of the Congo', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '52', 'country_label' => 'Cook Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '53', 'country_label' => 'Costa Rica', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '54', 'country_label' => 'Cote d\'Ivoire', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '55', 'country_label' => 'Croatia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '56', 'country_label' => 'Cuba', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '57', 'country_label' => 'Cyprus', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '58', 'country_label' => 'Czech Republic', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '59', 'country_label' => 'Denmark', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '60', 'country_label' => 'Djibouti', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '61', 'country_label' => 'Dominica', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '62', 'country_label' => 'Dominican Republic', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '63', 'country_label' => 'Ecuador', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '64', 'country_label' => 'Egypt', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '65', 'country_label' => 'El Salvador', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '66', 'country_label' => 'Equatorial Guinea', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '67', 'country_label' => 'Eritrea', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '68', 'country_label' => 'Estonia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '69', 'country_label' => 'Ethiopia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '70', 'country_label' => 'Falkland Islands (Malvinas)', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '71', 'country_label' => 'Faroe Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '72', 'country_label' => 'Fiji', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '73', 'country_label' => 'Finland', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '74', 'country_label' => 'France', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '75', 'country_label' => 'French Guiana', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '76', 'country_label' => 'French Polynesia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '77', 'country_label' => 'Gabon', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '78', 'country_label' => 'Gambia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '79', 'country_label' => 'Georgia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '80', 'country_label' => 'Germany', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '81', 'country_label' => 'Ghana', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '82', 'country_label' => 'Gibraltar', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '83', 'country_label' => 'Greece', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '84', 'country_label' => 'Greenland', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '85', 'country_label' => 'Grenada', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '86', 'country_label' => 'Guadeloupe', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '87', 'country_label' => 'Guam', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '88', 'country_label' => 'Guatemala', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '89', 'country_label' => 'Guernsey', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '90', 'country_label' => 'Guinea', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '91', 'country_label' => 'Guinea-Bissau', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '92', 'country_label' => 'Guyana', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '93', 'country_label' => 'Haiti', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '94', 'country_label' => 'Holy See (Vatican City State)', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '95', 'country_label' => 'Honduras', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '96', 'country_label' => 'Hong Kong', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '97', 'country_label' => 'Hungary', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '98', 'country_label' => 'Iceland', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '99', 'country_label' => 'India', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '100', 'country_label' => 'Indonesia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '101', 'country_label' => 'Iran, Islamic Republic of Persian Gulf', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '102', 'country_label' => 'Iraq', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '103', 'country_label' => 'Ireland', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '104', 'country_label' => 'Isle of Man', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '105', 'country_label' => 'Israel', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '106', 'country_label' => 'Italy', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '107', 'country_label' => 'Jamaica', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '108', 'country_label' => 'Japan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '109', 'country_label' => 'Jersey', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '110', 'country_label' => 'Jordan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '111', 'country_label' => 'Kazakhstan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '112', 'country_label' => 'Kenya', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '113', 'country_label' => 'Kiribati', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '114', 'country_label' => 'Korea, Democratic People\'s Republic of Korea', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '115', 'country_label' => 'Korea, Republic of South Korea', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '116', 'country_label' => 'Kuwait', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '117', 'country_label' => 'Kyrgyzstan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '118', 'country_label' => 'Laos', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '119', 'country_label' => 'Latvia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '120', 'country_label' => 'Lebanon', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '121', 'country_label' => 'Lesotho', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '122', 'country_label' => 'Liberia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '123', 'country_label' => 'Libyan Arab Jamahiriya', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '124', 'country_label' => 'Liechtenstein', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '125', 'country_label' => 'Lithuania', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '126', 'country_label' => 'Luxembourg', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '127', 'country_label' => 'Macao', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '128', 'country_label' => 'Macedonia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '129', 'country_label' => 'Madagascar', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '130', 'country_label' => 'Malawi', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '131', 'country_label' => 'Malaysia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '132', 'country_label' => 'Maldives', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '133', 'country_label' => 'Mali', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '134', 'country_label' => 'Malta', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '135', 'country_label' => 'Marshall Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '136', 'country_label' => 'Martinique', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '137', 'country_label' => 'Mauritania', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '138', 'country_label' => 'Mauritius', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '139', 'country_label' => 'Mayotte', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '140', 'country_label' => 'Mexico', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '141', 'country_label' => 'Micronesia, Federated States of Micronesia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '142', 'country_label' => 'Moldova', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '143', 'country_label' => 'Monaco', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '144', 'country_label' => 'Mongolia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '145', 'country_label' => 'Montenegro', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '146', 'country_label' => 'Montserrat', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '147', 'country_label' => 'Morocco', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '148', 'country_label' => 'Mozambique', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '149', 'country_label' => 'Myanmar', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '150', 'country_label' => 'Namibia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '151', 'country_label' => 'Nauru', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '152', 'country_label' => 'Nepal', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '153', 'country_label' => 'Netherlands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '154', 'country_label' => 'Netherlands Antilles', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '155', 'country_label' => 'New Caledonia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '156', 'country_label' => 'New Zealand', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '157', 'country_label' => 'Nicaragua', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '158', 'country_label' => 'Niger', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '159', 'country_label' => 'Niue', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '160', 'country_label' => 'Norfolk Island', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '161', 'country_label' => 'Northern Mariana Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '162', 'country_label' => 'Norway', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '163', 'country_label' => 'Oman', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '164', 'country_label' => 'Pakistan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '165', 'country_label' => 'Palau', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '166', 'country_label' => 'Palestinian Territory, Occupied', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '167', 'country_label' => 'Panama', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '168', 'country_label' => 'Papua New Guinea', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '169', 'country_label' => 'Paraguay', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '170', 'country_label' => 'Peru', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '171', 'country_label' => 'Philippines', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '172', 'country_label' => 'Pitcairn', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '173', 'country_label' => 'Poland', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '174', 'country_label' => 'Portugal', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '175', 'country_label' => 'Puerto Rico', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '176', 'country_label' => 'Qatar', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '177', 'country_label' => 'Romania', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '178', 'country_label' => 'Russia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '179', 'country_label' => 'Rwanda', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '180', 'country_label' => 'Reunion', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '181', 'country_label' => 'Saint Barthelemy', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '182', 'country_label' => 'Saint Helena, Ascension and Tristan Da Cunha', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '183', 'country_label' => 'Saint Kitts and Nevis', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '184', 'country_label' => 'Saint Lucia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '185', 'country_label' => 'Saint Martin', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '186', 'country_label' => 'Saint Pierre and Miquelon', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '187', 'country_label' => 'Saint Vincent and the Grenadines', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '188', 'country_label' => 'Samoa', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '189', 'country_label' => 'San Marino', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '190', 'country_label' => 'Sao Tome and Principe', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '191', 'country_label' => 'Saudi Arabia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '192', 'country_label' => 'Senegal', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '193', 'country_label' => 'Serbia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '194', 'country_label' => 'Seychelles', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '195', 'country_label' => 'Sierra Leone', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '196', 'country_label' => 'Singapore', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '197', 'country_label' => 'Slovakia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '198', 'country_label' => 'Slovenia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '199', 'country_label' => 'Solomon Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '200', 'country_label' => 'Somalia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '201', 'country_label' => 'South Africa', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '202', 'country_label' => 'South Sudan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '203', 'country_label' => 'South Georgia and the South Sandwich Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '204', 'country_label' => 'Spain', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '205', 'country_label' => 'Sri Lanka', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '206', 'country_label' => 'Sudan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '207', 'country_label' => 'Suricountry_label', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '208', 'country_label' => 'Svalbard and Jan Mayen', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '209', 'country_label' => 'Swaziland', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '210', 'country_label' => 'Sweden', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '211', 'country_label' => 'Switzerland', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '212', 'country_label' => 'Syrian Arab Republic', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '213', 'country_label' => 'Taiwan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '214', 'country_label' => 'Tajikistan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '215', 'country_label' => 'Tanzania, United Republic of Tanzania', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '216', 'country_label' => 'Thailand', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '217', 'country_label' => 'Timor-Leste', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '218', 'country_label' => 'Togo', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '219', 'country_label' => 'Tokelau', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '220', 'country_label' => 'Tonga', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '221', 'country_label' => 'Trinidad and Tobago', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '222', 'country_label' => 'Tunisia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '223', 'country_label' => 'Turkey', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '224', 'country_label' => 'Turkmenistan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '225', 'country_label' => 'Turks and Caicos Islands', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '226', 'country_label' => 'Tuvalu', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '227', 'country_label' => 'Uganda', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '228', 'country_label' => 'Ukraine', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '229', 'country_label' => 'United Arab Emirates', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '230', 'country_label' => 'United Kingdom', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '231', 'country_label' => 'United States', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '232', 'country_label' => 'Uruguay', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '233', 'country_label' => 'Uzbekistan', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '234', 'country_label' => 'Vanuatu', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '235', 'country_label' => 'Venezuela, Bolivarian Republic of Venezuela', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '236', 'country_label' => 'Vietnam', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '237', 'country_label' => 'Virgin Islands, British', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '238', 'country_label' => 'Virgin Islands, U.S.', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '239', 'country_label' => 'Wallis and Futuna', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '240', 'country_label' => 'Yemen', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '241', 'country_label' => 'Zambia', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '242', 'country_label' => 'Zimbabwe', 'created_by' => '1', 'is_deleted' => '0', 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL)
        );


        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('countries')->truncate();
        DB::table('countries')->insert($settings_countries);
    }
}
